CRM/CRM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('client/', include('clientModule.urls')),
    path('admin/', admin.site.urls),
]

CRM/clientModule/urls.py
from django.urls import path

from . import views

app_name = 'clientModule'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:client_id>/', views.detail, name='detail'),
    path('/edit/<int:client_id>/', views.edit, name='edit'),
]

CRM/clientModule/models.py
from django.db import models


class Client(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return "%s" % self.full_name


class Address(models.Model):
    street_name = models.CharField(max_length=200)
    house_number = models.CharField(max_length=5)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)

    def __str__(self):
        return "%s - %s" % (self.street_name, self.client)

CRM/clientModule/forms.py
from django import forms
from .models import Client, Address


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = "__all__"


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = "__all__"

CRM/clientModule/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect

from .forms import ClientForm
from .models import Client
# Create your views here.


def index(request):
    clients_list = Client.objects.order_by('full_name')[:5]
    context = {'clients_list': clients_list}
    return render(request, 'clientModule/index.html', context)


def detail(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    return render(request, 'clientModule/detail.html', {'client': client})


def edit(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    form = ClientForm(request.POST, instance=client)
    if form.is_valid():
        form.save()
        return redirect("clientModule/index")
    return render(request, 'clientModule/edit.html', {'client': client})

CRM/clientModule/templates/clientModule/detail.html
<h1>{{ client.full_name }}</h1>
<p>{{ client.email }}</p>
<p>{{ client.phone }}</p>
<ul>
    {% for address in client.address_set.all %}
        <li>{{ address.street_name }}</li>
    {% endfor %}
</ul>

CRM/clientModule/templates/clientModule/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Edit</title>

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'clientModule/bulma.min.css' %}">
</head>
<body>
    <form method="post" class="post-form" action="/update/{{client.id}}">
        {% csrf_token %}
        <div class="field">
            <label class="label">Nome</label>
            <div class="control">
                <input class="input" type="text" placeholder="Nome">
            </div>
        </div>
        <div class="field">
            <label class="label">Email</label>
            <div class="control">
                <input class="input" type="text" placeholder="Email">
            </div>
        </div>
        <div class="field">
            <label class="label">Telefone</label>
            <div class="control">
                <input class="input" type="text" placeholder="Telefone">
            </div>
        </div>
        <div class="control">
            <button class="button is-primary">Atualizar</button>
        </div>
    </form>
</body>
</html>

CRM/clientModule/templates/clientModule/index.html
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Index</title>

        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'clientModule/bulma.min.css' %}">
    </head>
    <body>
        {% if clients_list %}
    <ul>
        {% for client in clients_list %}
            <li><a href="{% url 'clientModule:detail' client.id %}">{{ client.full_name }}</a></li>
            <div class="control">
                <a class="button is-success" href="{% url 'clientModule:edit' client.id %}">Editar</a>
            </div>
        {% endfor %}
    </ul>
{% else %}
    <p>Nenhum cliente cadastrado.</p>
{% endif %}
    </body>
</html>